name: "Stack"

exports: "mootools-stack.js"

web: "[mooforum.net](http://mooforum.net)"

description: "MooTools Stack, a mooforum manifest"

license: "[MIT License](http://mootools.net/license.txt)"

copyright: "&copy; [mooforum](http://mooforum.net)"

authors: "Thomas Allmer"

sources:
  - "Source/Class/Class.Settings.js"
  - "Source/Class/Class.SubObjectMapping.js"
  - "Source/Visual/Overlay/Overlay.js"
  - "Source/Visual/PageZoom.js"
  - "Source/Galleries/Gallery/Gallery.js"
  - "Source/Galleries/FlexSlide/FlexSlide.js"
  - "Source/Galleries/FlexSlide/FlexSlide.Advanced.js"
  - "Source/Galleries/FlexSlide/FlexSlide.Transitions.js"
  - "Source/Galleries/FlexSlide/FlexSlides.js"
  - "Source/Galleries/FlexSlide/FlexSlides.Auto.js"
  - "Settings/Galleries/FlexSlide/SlideShow2/FlexSlide.Setting.SlideShow2.js"
  - "Settings/Galleries/FlexSlide/Tab/FlexSlide.Setting.Tab.js"
  - "Settings/Galleries/FlexSlide/TabVertical/FlexSlide.Setting.TabVertical.js"
  - "Source/Galleries/FlexBox/FlexBox.js"
  - "Source/Galleries/FlexBox/FlexBoxes.js"
  - "Settings/Galleries/FlexBox/LightBox/FlexBox.Setting.LightBox.js"
  - "Settings/Galleries/FlexBox/MediaBox/FlexBox.Setting.MediaBox.js"
  - "Source/Menus/MenuMatic.js"
  - "Source/Editor/Flexo/Flexo.js"
  - "Source/Visual/MooPath/Fx.Any.js"
  - "Source/Visual/MooPath/MooPath.js"
  - "Source/Visual/MooPath/MooPath.Ellipse.js"
  - "Source/Visual/MooPath/MooPath.Wave.js"
  - "Source/Interface/HtmlTables.js"
  - "Source/Interface/ScrollBar/ScrollBar.js"
  - "Source/Interface/ScrollBar/ScrollBars.js"
  - "Source/Interface/Map/Map.js"
  - "Source/Interface/Map/Map.Marker.js"
  - "Source/Interface/Map/Map.InfoWindow.js"
  - "Source/Interface/Map/Map.Polygon.js"
  - "Source/Interface/Map/Map.Circle.js"
  - "Source/Interface/Map/Map.Rectangle.js"
  - "Source/Interface/Map/Map.PolyLine.js"
  - "Source/Interface/Map/Map.Geocoder.js"
  - "Source/Interface/Map/Map.InfoMarker.js"
  - "Source/Interface/Map/Map.Plugin.Bounds.js"
  - "Source/Interface/Map/Map.Plugin.Play.js"
  - "Source/Form/DatePicker.js"
  - "Source/Form/Select.js"
  - "Source/Form/Selects.js"
  - "Source/Element/Element.OuterClick.js"
  - "Source/Behaviors/Behavior.FlexSlide.js"
  - "Source/Behaviors/Behavior.FlexBox.js"
  - "Source/Behaviors/Behavior.DatePicker.js"
  - "Source/Behaviors/Behavior.DatePickerGerman.js"
  - "Source/Behaviors/Behavior.ImageFullDownload.js"
  - "Source/Plugins/Plugin.GermanHtmlTable.js"
  - "Source/Behaviors/Behavior.SearchSelect.js"
  - "Source/Behaviors/Behavior.Styling.js"
  - "Source/Behaviors/Behavior.Zoom.js"
  - "Source/Behaviors/Behavior.Map.js"
  - "Source/Behaviors/Behavior.PolyLine.js"
  - "Source/Behaviors/Behavior.Point.js"
  - "Source/Delegators/Delegator.Tweening.js"
  - "Source/Delegators/Delegator.Styling.js"
  - "Source/Delegators/Delegator.Print.js"
  - "Source/Delegators/Delegator.Zoom.js"
