name: "Stack"
exports: "mootools-stack.js"
web: "[mooforum.net](http://mooforum.net)"
description: "MooTools Stack, a mooforum manifest"
license: "[MIT License](http://mootools.net/license.txt)"
copyright: "&copy; [mooforum](http://mooforum.net)"
authors: "[Thomas Allmer](http://mooforum.net)"

sources:
  - "Source/Visual/PageZoom.js"
  - "Source/Menus/MenuMatic.js"
  - "Source/Visual/MooPath/Fx.Any.js"
  - "Source/Visual/MooPath/MooPath.js"
  - "Source/Visual/MooPath/MooPath.Ellipse.js"
  - "Source/Visual/MooPath/MooPath.Wave.js"
  - "Source/Interface/ScrollBar/ScrollBar.js"
  - "Source/Interface/ScrollBar/ScrollBars.js"
  - "Source/Form/Select/Select.js"
  - "Source/Form/Select/Selects.js"
  - "Source/Element/Element.OuterClick.js"
  - "Source/Behaviors/Behavior.FormRequest.js"
  - "Source/Behaviors/Behavior.FlexBox.js"
  - "Source/Behaviors/Behavior.DatePicker.js"
  - "Source/Behaviors/Behavior.ImageFullDownload.js"
  - "Source/Behaviors/Behavior.SearchSelect.js"
  - "Source/Behaviors/Behavior.Style.js"
  - "Source/Behaviors/Behavior.equal-style.js"
  - "Source/Behaviors/Behavior.absolute-center.js"
  - "Source/Behaviors/Behavior.DropMenu.js"
  - "Source/Behaviors/Behavior.Position.js"
  - "Source/Behaviors/Behavior.Nudging.js"
  - "Source/Behaviors/Behavior.Zoom.js"
  - "Source/Behaviors/Behavior.SmoothScroll.js"
  - "Source/Behaviors/Behavior.OnlyOnce.js"
  - "Source/Delegators/Delegator.tween.js"
  - "Source/Delegators/Delegator.class.js"
  - "Source/Delegators/Delegator.Style.js"
  - "Source/Delegators/Delegator.Print.js"
  - "Source/Delegators/Delegator.Zoom.js"
  - "Source/Delegators/Delegator.SyncSelect.js"
  - "Source/Delegators/Delegator.SubmitChangedSelect.js"
  - "Source/Delegators/Delegator.GoToChangedSelect.js"
  - "Source/Delegators/Delegator.Stop.js"